// <auto-generated />
using System;
using DungeonsAndDragons.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DungeonsAndDragons.Migrations
{
    [DbContext(typeof(DungeonsAndDragonsContext))]
    [Migration("20181211143435_GameClass")]
    partial class GameClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DungeonsAndDragons.Models.Game", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("dm_id");

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("dm_id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("DungeonsAndDragons.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("username")
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DungeonsAndDragons.Models.Game", b =>
                {
                    b.HasOne("DungeonsAndDragons.Models.User", "dm_")
                        .WithMany()
                        .HasForeignKey("dm_id");
                });
#pragma warning restore 612, 618
        }
    }
}
